name: MLOps CI Pipeline

on:
  push:
    branches: [ main ]

jobs:

  test_suite:
    name: Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          pytest -s tests/test_train.py
        env:
          PYTHONPATH: .

  train_and_quantize:
    name: Train and Quantize
    runs-on: ubuntu-latest
    needs: test_suite

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Training
        run: python src/train.py

      - name: Run Quantization
        run: python src/quantize.py

  build_and_test_container:
    name: Build & Test Container
    runs-on: ubuntu-latest
    needs: train_and_quantize

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t mlops-final .

      - name: Run Container to Predict
        run: docker run --rm mlops-final
